version: '2.4'  # The last version of Docker Compose file format that directly supports mem_limit and cpus
services:
  counter-service:
    container_name: my-counter-service
    image: 246988968739.dkr.ecr.us-east-1.amazonaws.com/counter-service:latest
    volumes:
      -  /home/runner/work/counter-service/counter-service/data:/app/data
    ports:
      - "80:8080"
    restart: always
    mem_limit: 256M
    cpus: 0.5
